# Generated by Django 5.2 on 2025-04-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='profissionais.profissional'),
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
    ]
